# Generated by Django 2.0.5 on 2018-06-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trackr', '0002_auto_20180605_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moodentry',
            name='enteredOn',
            field=models.DateTimeField(),
        ),
    ]
